package com.makkajai.makkajai.printer;

import com.makkajai.makkajai.model.receipt.Receipt;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

/**
 * ReceiptPrinter.java
 *
 * Handles the presentation logic for printing receipt details.
 *
 * Responsibilities:
 * - Iterates over each printable line generated by the Receipt object.
 * - Logs each line using the SLF4J logger (instead of using System.out).
 *
 * Purpose:
 * - Keeps I/O concerns (e.g., printing/logging) separate from business logic.
 * - Makes the application easier to test and maintain by isolating output behavior.
 *
 * Usage:
 * - Call printReceipt(Receipt) to log the final formatted receipt after items are added.
 */


public class ReceiptPrinter {
    private static final Logger logger = LoggerFactory.getLogger(ReceiptPrinter.class);

    public static void printReceipt(Receipt receipt) {
        for (String line : receipt.getPrintableLines()) {
            logger.info(line);
        }
    }
}